### ISSUE TITLE
Exception caught by image resource service

### ISSUE THREAD

**Issue by ricardobarrospereira** [josxha/flutter_map_cache#3]
Hi! I'm new to Flutter so I am probably missing something, but I am trying to use FileSystem cache exactly as it is showing on [this example](https://github.com/josxha/flutter_map_cache/wiki/Use-the-File-System), and it is showing a lot of the exceptions below every time the map loads:

════════ Exception caught by image resource service ════════════════════════════
DioException [request cancelled]: The request was cancelled.

It doesn't show any other detail, only those lines repeating multiple times. This is happening both with File System and In Memory cache, for Android and iOS simulators.

What could be the cause of this?
Thanks!

**Comment by MaxiStefan** [comment]
Hi, i've also just started using this caching plugin and I am using the hive storage. Also ran into this exception

**Comment by josxha** [comment]
Hi @ricardobarrospereira and @MaxiStefan.
Thanks for the issue and sorry for my late response. I've had lots of things to do the last week.

### Quick answer: 
You can just ignore those exceptions in the console. The plugin still works as intended and I'm going to remove those console logs in the next version.

### Longer answer: 
flutter_map version 6 introduced an awesome new feature to cancel tile requests that aren't needed any more before they finished. This saves bandwidth, supports faster map loading times on the web and decreases costs on map providers. 

Tile requests are cancelled for example if you zoom in or out quickly and "skip" some zoom levels. The tiles from the between zoom level will get cancelled. And end up in a thrown exception that doesn't get caught internally. This is no problem and everything should work fine but I agree that it's confusing to users. I will release an update as soon as I find the time. For now you can just ignore it.

I hope that helps and sorry for this. (:

**Comment by josxha** [comment]
I published version `1.3.1` to pub.dev that removes those exceptions from the console. 👍

**Comment by maotou316** [comment]
I am using version 1.3.1, but the issue still persists. 

DioException (DioException [request cancelled]: The request was cancelled.)

![image](https://github.com/josxha/flutter_map_cache/assets/28297458/33cfbabc-3eb2-4ff6-87a2-5b2614525839)

**Comment by josxha** [comment]
@maotou316 Thanks for the comment. I created https://github.com/josxha/flutter_map_cache/issues/5, since the problem you are mentioning has actually a different cause and is vs code specific. It's a bug in the vs code debugger and can be ignored.
